# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='service.proto',
    package='alpha_zero',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rservice.proto\x12\nalpha_zero\":\n\x10InferenceRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0bobservation\x18\x02 \x01(\x0c\"x\n\x11InferenceResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x1c\n\x14status_error_message\x18\x03 \x01(\t\x12\x0e\n\x06policy\x18\x04 \x01(\x0c\x12\r\n\x05value\x18\x05 \x01(\x05\"\x99\x01\n\x14UpdateWeightsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12>\n\x07weights\x18\x02 \x03(\x0b\x32-.alpha_zero.UpdateWeightsRequest.WeightsEntry\x1a.\n\x0cWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"]\n\x15UpdateWeightsResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x1c\n\x14status_error_message\x18\x03 \x01(\t2\xb5\x01\n\x0e\x43\x65ntralService\x12J\n\tinference\x12\x1c.alpha_zero.InferenceRequest\x1a\x1d.alpha_zero.InferenceResponse\"\x00\x12W\n\x0eupdate_weights\x12 .alpha_zero.UpdateWeightsRequest\x1a!.alpha_zero.UpdateWeightsResponse\"\x00\x62\x06proto3',
)


_INFERENCEREQUEST = _descriptor.Descriptor(
    name='InferenceRequest',
    full_name='alpha_zero.InferenceRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='client_id',
            full_name='alpha_zero.InferenceRequest.client_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b''.decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='observation',
            full_name='alpha_zero.InferenceRequest.observation',
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b'',
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=29,
    serialized_end=87,
)


_INFERENCERESPONSE = _descriptor.Descriptor(
    name='InferenceResponse',
    full_name='alpha_zero.InferenceResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='client_id',
            full_name='alpha_zero.InferenceResponse.client_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b''.decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='status_code',
            full_name='alpha_zero.InferenceResponse.status_code',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='status_error_message',
            full_name='alpha_zero.InferenceResponse.status_error_message',
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b''.decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='policy',
            full_name='alpha_zero.InferenceResponse.policy',
            index=3,
            number=4,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b'',
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='value',
            full_name='alpha_zero.InferenceResponse.value',
            index=4,
            number=5,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=89,
    serialized_end=209,
)


_UPDATEWEIGHTSREQUEST_WEIGHTSENTRY = _descriptor.Descriptor(
    name='WeightsEntry',
    full_name='alpha_zero.UpdateWeightsRequest.WeightsEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='key',
            full_name='alpha_zero.UpdateWeightsRequest.WeightsEntry.key',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b''.decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='value',
            full_name='alpha_zero.UpdateWeightsRequest.WeightsEntry.value',
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b'',
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b'8\001',
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=319,
    serialized_end=365,
)

_UPDATEWEIGHTSREQUEST = _descriptor.Descriptor(
    name='UpdateWeightsRequest',
    full_name='alpha_zero.UpdateWeightsRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='client_id',
            full_name='alpha_zero.UpdateWeightsRequest.client_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b''.decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='weights',
            full_name='alpha_zero.UpdateWeightsRequest.weights',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _UPDATEWEIGHTSREQUEST_WEIGHTSENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=212,
    serialized_end=365,
)


_UPDATEWEIGHTSRESPONSE = _descriptor.Descriptor(
    name='UpdateWeightsResponse',
    full_name='alpha_zero.UpdateWeightsResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='client_id',
            full_name='alpha_zero.UpdateWeightsResponse.client_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b''.decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='status_code',
            full_name='alpha_zero.UpdateWeightsResponse.status_code',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='status_error_message',
            full_name='alpha_zero.UpdateWeightsResponse.status_error_message',
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b''.decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=367,
    serialized_end=460,
)

_UPDATEWEIGHTSREQUEST_WEIGHTSENTRY.containing_type = _UPDATEWEIGHTSREQUEST
_UPDATEWEIGHTSREQUEST.fields_by_name['weights'].message_type = _UPDATEWEIGHTSREQUEST_WEIGHTSENTRY
DESCRIPTOR.message_types_by_name['InferenceRequest'] = _INFERENCEREQUEST
DESCRIPTOR.message_types_by_name['InferenceResponse'] = _INFERENCERESPONSE
DESCRIPTOR.message_types_by_name['UpdateWeightsRequest'] = _UPDATEWEIGHTSREQUEST
DESCRIPTOR.message_types_by_name['UpdateWeightsResponse'] = _UPDATEWEIGHTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferenceRequest = _reflection.GeneratedProtocolMessageType(
    'InferenceRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _INFERENCEREQUEST,
        '__module__': 'service_pb2'
        # @@protoc_insertion_point(class_scope:alpha_zero.InferenceRequest)
    },
)
_sym_db.RegisterMessage(InferenceRequest)

InferenceResponse = _reflection.GeneratedProtocolMessageType(
    'InferenceResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _INFERENCERESPONSE,
        '__module__': 'service_pb2'
        # @@protoc_insertion_point(class_scope:alpha_zero.InferenceResponse)
    },
)
_sym_db.RegisterMessage(InferenceResponse)

UpdateWeightsRequest = _reflection.GeneratedProtocolMessageType(
    'UpdateWeightsRequest',
    (_message.Message,),
    {
        'WeightsEntry': _reflection.GeneratedProtocolMessageType(
            'WeightsEntry',
            (_message.Message,),
            {
                'DESCRIPTOR': _UPDATEWEIGHTSREQUEST_WEIGHTSENTRY,
                '__module__': 'service_pb2'
                # @@protoc_insertion_point(class_scope:alpha_zero.UpdateWeightsRequest.WeightsEntry)
            },
        ),
        'DESCRIPTOR': _UPDATEWEIGHTSREQUEST,
        '__module__': 'service_pb2'
        # @@protoc_insertion_point(class_scope:alpha_zero.UpdateWeightsRequest)
    },
)
_sym_db.RegisterMessage(UpdateWeightsRequest)
_sym_db.RegisterMessage(UpdateWeightsRequest.WeightsEntry)

UpdateWeightsResponse = _reflection.GeneratedProtocolMessageType(
    'UpdateWeightsResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _UPDATEWEIGHTSRESPONSE,
        '__module__': 'service_pb2'
        # @@protoc_insertion_point(class_scope:alpha_zero.UpdateWeightsResponse)
    },
)
_sym_db.RegisterMessage(UpdateWeightsResponse)


_UPDATEWEIGHTSREQUEST_WEIGHTSENTRY._options = None

_CENTRALSERVICE = _descriptor.ServiceDescriptor(
    name='CentralService',
    full_name='alpha_zero.CentralService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=463,
    serialized_end=644,
    methods=[
        _descriptor.MethodDescriptor(
            name='inference',
            full_name='alpha_zero.CentralService.inference',
            index=0,
            containing_service=None,
            input_type=_INFERENCEREQUEST,
            output_type=_INFERENCERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='update_weights',
            full_name='alpha_zero.CentralService.update_weights',
            index=1,
            containing_service=None,
            input_type=_UPDATEWEIGHTSREQUEST,
            output_type=_UPDATEWEIGHTSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CENTRALSERVICE)

DESCRIPTOR.services_by_name['CentralService'] = _CENTRALSERVICE

# @@protoc_insertion_point(module_scope)
